version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install --requirement dev_requirements.txt
            ./dev-scripts/build
      - run:
          name: install coveralls and upload coverage information
          command: |
            . venv/bin/activate
            pip install coveralls==3.0.1
            coveralls
  e2e:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install bzip2
          command: sudo apt-get install bzip2
      - run:
          name: Download restic
          command: |
            wget https://github.com/restic/restic/releases/download/v0.12.0/restic_0.12.0_linux_amd64.bz2
            bzip2 -d restic_0.12.0_linux_amd64.bz2
            chmod +x restic_0.12.0_linux_amd64
            sudo mv restic_0.12.0_linux_amd64 /usr/local/bin/restic
      - run:
          name: Install from setup.py and run end-to-end tests
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install .
            ./e2e/test.py
  prepare_pypi_package:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            set -x
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install \
              setuptools==54.2.0 \
              wheel==0.36.2 \
              twine==3.4.1
            python setup.py sdist bdist_wheel
            twine check dist/*
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - dist
  publish:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: publish to PyPI
          # Requires TWINE_USERNAME and TWINE_PASSWORD environment variables.
          command: |
              set -x
              . venv/bin/activate
              twine upload dist/*
workflows:
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - e2e:
          filters:
            tags:
              only: /.*/
      - prepare_pypi_package:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
            - e2e
            - prepare_pypi_package
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){2}/
            branches:
              ignore: /.*/
