version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install --requirement dev_requirements.txt
            ./dev-scripts/build
      - run:
          name: install coveralls
          command: pip install coveralls==3.0.1
      - run:
          name: upload coverage information to coveralls
          command: coveralls
  install:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install from setup.py
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install .
workflows:
  test:
    jobs:
      - build
      - install
